geoGuess/urls.py
from django.urls import path
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView

from .import views
from .views import Home, AdminUsersView, AddChallengeView, ChallengeBankView, AboutView
from .views import ViewSubmissions, ApproveSubmissionsView, LeaderboardView, DailyChallengeView, DailyChallengeListView, ProfileView


urlpatterns = [
    path("", Home.as_view(), name="home"),

    #these two are part of Google Oauth
    path('accounts/', include('allauth.urls')),
    path('logout', LogoutView.as_view()),

    ##REGULAR USER URLS##
    path('about/', AboutView.as_view(), name='about'),
    path('daily_challenges', DailyChallengeListView.as_view(), name="daily_challenge_list"),
    path('daily_challenge/<int:pk>/', DailyChallengeView.as_view(), name="daily_challenge"),
    path('submissions/', ViewSubmissions.as_view(), name="submissions"),
    path('challenge_form/', AddChallengeView.as_view(), name="challenge"),
    path('leaderboard/', LeaderboardView.as_view(), name="leaderboard"),
    path('user/<int:pk>/', ProfileView.as_view(), name="profile"),


    ##ADMIN URLS##
    path('admin_users/', AdminUsersView.as_view(), name="admin_users"),
    path('challenge_bank/', ChallengeBankView.as_view(), name="challenge_bank"),
    path('edit_user/<int:user_id>/', views.edit_user, name='user_edit'),
    path('challenge_feedback/<int:challenge_id>/', views.get_admin_feedback, name='admin_feedback'),
    path('approve_submissions/', ApproveSubmissionsView.as_view(), name="approve_submissions"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("geoGuess.urls")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geoGuess/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator
from django.db.models.signals import pre_save
from django.dispatch import receiver
from geopy.distance import geodesic
import math

class Challenge(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)    # Link to the user who created the challenge
    image = models.ImageField(upload_to='challenges/')          # Store the uploaded image
    longitude = models.FloatField()
    latitude = models.FloatField()                              # Store the answer coordinates
    timestamp = models.DateTimeField(auto_now_add=True)         # Automatically set when the challenge is created
    approve_status = models.BooleanField(default=False)         # whether or not challenge has been approved
    approval_feedback = models.TextField(default="")            # the feedback given by admin if challenge was denied

    def __str__(self):
        return f"Challenge {self.pk} by {self.user.username}"

    class Meta:
        verbose_name = "Challenge"
        verbose_name_plural = "Challenges"

class DailyChallenge(models.Model):
    challenge = models.ForeignKey(Challenge, on_delete=models.CASCADE)  # Links to the challenge
    timestamp = models.DateTimeField(auto_now_add=True)                 # Automatically set when the daily challenge is created
    def __str__(self):
        return f"Daily Challenge {self.pk} from {self.timestamp}"

    def get_leaderboard(self):
        # Retrieve all guesses for the associated challenge, ordered by score descending
        guesses = Guess.objects.filter(challenge=self.challenge).order_by('-score')
        leaderboard = [
            {'username': guess.user.username, 'score': guess.score, "id": guess.user.id, 'name': guess.user.first_name, }
            for guess in guesses
        ]
        return leaderboard




class Guess(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    challenge = models.ForeignKey(Challenge, on_delete=models.CASCADE)
    score = models.IntegerField(default=0, validators=[MinValueValidator(limit_value=0, message='Score must be greater than or equal to 0')])                # Store the score / 1000 Automatically Calculated
    distanceFromAnswer = models.FloatField(default=0, validators=[MinValueValidator(limit_value=0.0, message='Distance must be greater than or equal to 0')])# Store in meters, Automatically Calculated
    longitude = models.FloatField(default=0)                            # Store the guessed coordinates
    latitude = models.FloatField(default=0)                             # Store the  coordinates

    def __str__(self):
        return f"Guess {self.pk} by {self.user.username}"

# Functions to automatically calculate score and distance when a guess is saved
@receiver(pre_save, sender=Guess)
def calculate_distance_score(sender, instance, **kwargs):
    distance = get_distance(instance.latitude, instance.longitude, instance.challenge.latitude, instance.challenge.longitude)
    instance.score = calculate_score(distance)
    instance.distanceFromAnswer = distance

pre_save.connect(calculate_distance_score, sender=Guess)

# Uses geopy to get the distance between two coordinates in METERS
def get_distance(lat1, lon1, lat2, lon2):
    return geodesic((lat1, lon1), (lat2, lon2)).meters

# Calculates the score / 1000 based on the distance from the correct answer in METERS
def calculate_score(distance):
    max_score = 1000
    max_score_range = 10
    dropoff_rate = 400

    # Max score is 1000, will give the max score if within 10 meters
    return min(int(max_score * math.exp(-(distance - max_score_range) / dropoff_rate)), max_score)

geoGuess/forms.py
from django import forms
from .models import Guess, Challenge

class ChallengeForm(forms.ModelForm):
    class Meta:
        model = Challenge
        fields = ['image', 'longitude', 'latitude']
        
class GuessForm(forms.ModelForm):
    class Meta:
        model = Guess
        fields = ['latitude', 'longitude']
        
class ApproveChallengeForm(forms.ModelForm):
    class Meta:
        model = Challenge
        fields = ['approve_status', 'approval_feedback']

class UserAuthForm(forms.Form):
    admin = forms.BooleanField(label="admin")
    

geoGuess/views.py
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.db.models import Q
from .models import Challenge, Guess, DailyChallenge
from django.views import generic
from django.urls import reverse
from django.shortcuts import render, redirect, get_object_or_404
from .forms import ChallengeForm, ApproveChallengeForm
import os


# Checks if the user has guessed a challenge
def hasBeenGuessed(challenge, user):
    return Guess.objects.filter(user=user, challenge=challenge).exists()

def rating_calc(average_score, games_played):
    # Determines how much weight to give to average score vs max score for leaderboard
    weight = 0.8
    return int((weight * average_score) + ((1 - weight) * games_played * average_score))



# Gets the leaderboard of players
def get_leaderboard():
    user_list = User.objects.all()
    guess_list = Guess.objects.all()
    user_stats = {}
    for guess in guess_list:
        username = guess.user.username
        if username not in user_stats:
            user_stats[username] = {"score": 0, "games_played": 0}

        user_stats[username]["games_played"] += 1
        user_stats[username]["score"] += guess.score

    leaderboard = []
    for user in user_list:
        if(user.username in user_stats):
            games_played = user_stats[user.username]["games_played"]
            average_score = 0
            if(games_played != 0):
                average_score = user_stats[user.username]["score"] / games_played

            # Calculate rating based on average score and games played (Can be changed in the future)
            rating = rating_calc(average_score, games_played)

            leaderboard.append({"name": user.first_name, 
                                "average_score": int(average_score), 
                                "games_played": int(games_played), 
                                "rating": int(rating),
                                "id": user.id})
    return sorted(leaderboard, key=lambda x: x['rating'], reverse=True)

# Gets the statistics for an individual player
def get_player_stats(user):
    guess_list = Guess.objects.filter(user=user)
    games_played = guess_list.count()
    average_score = 0
    if(games_played != 0):
        average_score = sum([guess.score for guess in guess_list]) / games_played

    return {"games_played": games_played, "average_score": average_score, "rating": rating_calc(average_score, games_played)}
def get_user_leaderboard_position(user):
    leaderboard = get_leaderboard()
    for index, entry in enumerate(leaderboard, start = 1):
        if entry['id'] == user.id:
            return index
    return None
def get_recent_guesses(user):
    guess_list = Guess.objects.filter(user=user).order_by('-id')[:5]
    # This will add the daily_challenge information to each guess
    for guess in guess_list:
        guess.daily_challenge = DailyChallenge.objects.filter(challenge=guess.challenge).first()
    return guess_list


#Home View
class Home(generic.TemplateView):
    template_name = "home.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            player_stats = get_player_stats(self.request.user)
            context['player_stats'] = get_player_stats(self.request.user)
            context['leaderboard_position'] = get_user_leaderboard_position(self.request.user)
        return context
#About View
class AboutView(generic.TemplateView):
    template_name = "user/about.html"

# View to add a challenge
class AddChallengeView(LoginRequiredMixin, UserPassesTestMixin, generic.CreateView):
    template_name = 'user/challenge.html'
    login_url = '/'

    form_class = ChallengeForm
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['maps_api_key'] = os.environ.get('GOOGLE_MAPS_API_KEY')
        return context
    
    def post(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        if form.is_valid() and request.user.is_authenticated:
            challenge = form.save(commit=False)
            challenge.user = request.user
            challenge.save()
            return self.form_valid(form)
        else:
            return self.form_invalid(form)
    def form_valid(self, form):
        self.object = form.save(commit=False)
        form.save(commit=True)
        return redirect("submissions")   # Redirect to homepage or any other page after saving
    def form_invalid(self, form):
        return self.render_to_response(
            self.get_context_data()
        )
    
    def test_func(self):
        return self.request.user.is_authenticated and not self.request.user.is_staff
    
# View to see past challenges and current challenge
class DailyChallengeListView(LoginRequiredMixin, UserPassesTestMixin, generic.ListView):
    template_name = "user/daily_challenge_list.html"
    login_url = '/'
    context_object_name = "daily_challenge_list"

    def get_queryset(self):
        return DailyChallenge.objects.filter(challenge__approve_status=True)
    
    def test_func(self):
        return self.request.user.is_authenticated and not self.request.user.is_staff

# View to see a specific daily challenge
class DailyChallengeView(LoginRequiredMixin, UserPassesTestMixin, generic.DetailView):
    template_name = "user/daily_challenge.html"
    login_url = '/'
    model = DailyChallenge

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        daily_challenge = self.get_object()

        """
        Created with help from GPT 3, regarding linking users and their ids to help with profile redirection, ends at 
        line 165.
        """

        challenge_creator = daily_challenge.challenge.user
        context['challenge_creator_name'] = challenge_creator.first_name
        context['challenge_creator_id'] = challenge_creator.id

        leaderboard_ids = [player['id'] for player in daily_challenge.get_leaderboard()]

        is_creator_in_leaderboard = daily_challenge.challenge.user.id in leaderboard_ids

        context['is_creator_in_leaderboard'] = is_creator_in_leaderboard
        context['challenge_creator'] = daily_challenge.challenge.user


        context['daily_leaderboard'] = daily_challenge.get_leaderboard()
        context['maps_api_key'] = os.environ.get('GOOGLE_MAPS_API_KEY')
        # Sets information for the challenge being used
        context['Challenge'] = self.get_object().challenge
        context['DailyChallenge'] = DailyChallenge.objects.get(challenge=self.get_object().challenge)

        # If the user has guessed, include the guess in the context
        if self.request.user.is_authenticated:
            guess = Guess.objects.filter(user=self.request.user, challenge=daily_challenge.challenge).first()
            context['Guess'] = guess

        print(self.get_template_names())
        if 'user/daily_challenge_guessed.html' in self.get_template_names():
            context['Guess'] = Guess.objects.get(user=self.request.user, challenge=self.get_object().challenge)
        return context

    def post(self, request, *args, **kwargs):
        longitude = request.POST.get('longitude')
        latitude = request.POST.get('latitude')
        challenge = self.get_object().challenge

        if longitude != '' and latitude != '':
            # TODO: add checks for the latitude and longitude to make sure they are valid            
            guess = Guess(user=request.user, challenge=challenge, longitude=longitude, latitude=latitude)
            guess.save()
            return redirect("daily_challenge", pk=self.get_object().pk)
         
        # TODO: can make this with less repeated code.
        return render(
            request,
            self.template_name,
            {
                'Challenge': challenge,
                'maps_api_key': os.environ.get('GOOGLE_MAPS_API_KEY'),
            }
        )

    def get_template_names(self):
        if(hasBeenGuessed(self.get_object().challenge, self.request.user)):
            return ["user/daily_challenge_guessed.html"]
        
        return ["user/daily_challenge.html"]
    
    def test_func(self):
        return self.request.user.is_authenticated and not self.request.user.is_staff

class ViewSubmissions(LoginRequiredMixin, UserPassesTestMixin, generic.ListView):
    template_name = "user/viewSubmissions.html"
    login_url = '/'

    context_object_name = "challenges"

    # get all google registered users
    def get_queryset(self):
        return Challenge.objects.order_by('-id').filter(user=self.request.user)
    
    def test_func(self):
        return self.request.user.is_authenticated and not self.request.user.is_staff

class LeaderboardView(LoginRequiredMixin, UserPassesTestMixin, generic.ListView):
    template_name = "leaderboard.html"
    context_object_name = "leaderboard"
    
    def get_queryset(self):
        return get_leaderboard()
    
    def test_func(self):
        return self.request.user.is_authenticated and not self.request.user.is_staff


class ProfileView(generic.DetailView, UserPassesTestMixin):
    template_name = "user/profile.html"
    context_object_name = "user"

    def get_queryset(self):
        return User.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['stats'] = get_player_stats(self.get_object())

        # Retrieve the recent guesses and attach the related DailyChallenge
        recent_guesses_with_challenge = []
        for guess in get_recent_guesses(self.get_object()):
            # Try to get the related DailyChallenge

geoGuess/templates/user/about.html
{% extends 'base.html' %}
{% load static %}
{% load socialaccount %}
{% block content %}
<link rel="stylesheet" href="{% static 'geoGuess.css' %}" type="text/css" />
<style>
  .card {
    border-radius: 20px;
    box-shadow: 0 8px 16px rgba(0, 0, 0, 0.1), 0 0 25px #4285F4, 0 0 50px #4285F4; 
  }
</style>

<title>About HoosWhere?</title>
<link rel="stylesheet" href="{% static 'geoGuess.css' %}" type="text/css" />

<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card p-5 mb-5">
          <h1>About HoosWhere?</h1>
          <p>
              HoosWhere? is a geoguesser game designed specifically for the UVA community. It challenges students
              to put their campus knowledge to the test by identifying different locations around the University of
              Virginia based on images.
          </p>
          <h2>How to Play</h2>
          <ol>
              <li>Start the game by clicking on Daily Challenge!</li>
              <li>You will be presented multiple challenges. You can play past challenges or the daily challenge.</li>
              <li>Your task is to guess the location by placing a pin on the provided map.</li>
              <li>Submit your guess to see how close you were to the actual location by clicking on submit challenge.</li>
              <li>Earn points based on how accurate your guess was and climb up the leaderboard!</li>
          </ol>
          <p>
            We also encourage you to create your own challenges, and if they are approved, they will appear as a Daily Challenge for other users in the future!
          </p>
          <p>
              Whether you're a new student or a seasoned Hoo, this game is a fun way to explore the campus, learn
              about new spots, and see how well you really know UVA. Get guessing and go Hoos!
          </p>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

geoGuess/templates/user/challenge.html
{% extends 'base.html' %}
{% block content %}
<title>Create Challenge</title>

<!-- Google Maps CSS -->
{% load static %}
<link rel="stylesheet" href="{% static 'geoGuess.css' %}" type="text/css"/>

<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="exclamation-triangle-fill" viewBox="0 0 16 16">
        <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
    </symbol>
</svg>

<!-- Google Maps API -->
<script src="https://maps.googleapis.com/maps/api/js?key={{ maps_api_key }}&callback=initialize&v=weekly"
        defer></script>
<body>
<div class="text-center my-3">
    <h2> Create Your Own Challenge</h2>
    <h6 class="mx-5"> In the space below, upload an image at UVA, you would like to be featured in a future challenge
        :)  Then, click below where the location is on the map. Once, you hit submit, you should be able to go to the "View Submissions" and see if your
        submission gets approved. </h6>
</div>
<div class ="text-center">
    <form id="form" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.formset.errors }}
        {{ form.non_field.errors }}
        <!-- Image Upload Field -->
        <div class="input-group mt-3 mx-auto" style="width: 25%;">
            <input type="file" name="image" id="id_image" class="form-control" id="inputGroupFile02" required>
        </div>
        <br>
        <!-- Hidden Longitude and Latitude Fields (filled by the map click) -->
        <input type="hidden" name="longitude" id="id_longitude">
        <input type="hidden" name="latitude" id="id_latitude">

        <!-- Map Div -->
        <div class="text-center" id="map" style=" width: 80%; height: 45vh; margin: 0 auto;"></div>
        <br>
        <div id="error-message" class="alert alert-danger align-items-center mx-auto" role="alert" style="display: none; max-width: 42%;">
            <svg class="bi flex-shrink-0 me-2" role="img" style="height: 20px; width: 20px;" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
            Please place a marker on the map for the corresponding image!
        </div>

        <button class="btn btn-primary mb-4" type="submit" value="Submit" class="my-3 text-white bg-primary">Submit</button>
    </form>
</div>
<!-- Google Maps Initialization -->
<script>
    var map;
    var marker;
    var form = document.getElementById("form")

    function initialize() {
        const defaultLocation = {lat: 38.0336, lng: -78.5080}; //can change locationvar mapOptions = {

        map = new google.maps.Map(document.getElementById("map"), {
            center: defaultLocation,
            mapTypeId: google.maps.MapTypeId.HYBRID,
            zoom: 18,
            labels: true,
        });
        map.setTilt(45);
        google.maps.event.addListener(map, 'click', function (event) {
            placeMarker(event.latLng);
        });

    }

    function placeMarker(location) {
        if (marker) {  // if marker exists, remove it
            marker.setMap(null);
        }
        marker = new google.maps.Marker({
            position: location,
            map: map
        });

        // Update the hidden form fields with the clicked coordinates
        document.getElementById('id_longitude').value = location.lng();
        document.getElementById('id_latitude').value = location.lat();
    }

    form.addEventListener("submit", function (event) {
        // Check if latitude and longitude are empty
        var latitude = document.getElementById('id_latitude').value;
        var longitude = document.getElementById('id_longitude').value;

        // Error message element
        var errorMessage = document.getElementById("error-message");

        if (!latitude || !longitude) {
            // Display an error message
            errorMessage.style.display = 'flex';
            errorMessage.style.color = "red";

            // Prevent form submission
            event.preventDefault();
        }
    });

    // This function will be called once the Google Maps script is loaded
    initialize();
</script>
</body>
{% endblock content %}

geoGuess/templates/user/daily_challenge.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'geoGuess.css' %}" type="text/css"/>
<body>
    {% load static %}
    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
        <symbol id="exclamation-triangle-fill" viewBox="0 0 16 16">
            <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
        </symbol>
    </svg>

    <!-- Google Maps API -->
    <script src="https://maps.googleapis.com/maps/api/js?key={{ maps_api_key }}&callback=initialize&v=weekly" defer></script>
    <title>📅Daily Challenge</title>
    <meta name="viewport" content="width=device-width, initial-scale=0.5" />
    <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
    <form id="form" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.formset.errors }}
        <!-- Hidden Longitude and Latitude Fields (filled by the map click) -->
        <input type="hidden" name="longitude" id="id_longitude" required>
        <input type="hidden" name="latitude" id="id_latitude" required>
        <div class="container text-center my-3">
            <div class="pb-2">
                <h1> {{ DailyChallenge.timestamp|date:"F d, Y"}} </h1>
                <h5> Challenge by
                    {% if Challenge.user.is_staff %}
                        Admin
                    {% else %}
                        <a href="{% url 'profile' Challenge.user.id %}">
                            {{ Challenge.user.first_name|default:Challenge.user.username }}
                        </a>
                    {% endif %}
                </h5>
            </div>   
            <div class="row">
                <div class="col-md-6">
                    <img src="{{Challenge.image.url}}" class="img-fluid" style="width: 100%; height: 350px; display: block; margin: 0 auto; border-radius: 5%; box-shadow: 0 8px 16px rgba(0, 0, 0, 0.1);">
                </div>
                <div class="col-md-6">
                    <div class="text-center" id="map" style="height: 350px; width: 100%; border-radius: 5%; box-shadow: 0 8px 16px rgba(0, 0, 0, 0.1);"></div>
                </div>
            </div>
            <div id="error-message" class="alert alert-danger align-items-center mx-auto mt-3" role="alert" style="display: none; max-width: 42%;">
                <svg class="bi flex-shrink-0 me-2" role="img" style="height: 20px; width: 20px;" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
                Must select part of the map!
            </div>
        </div>
        <button type="submit" value="Submit" id="guessButton" class="btn btn-primary mt-3 mx-auto d-block">Make a Guess</button>
    </form>


    {% load static %}
      <!-- Google Maps Initialization -->
        <script>
            var map;
            var marker;
            var form = document.getElementById("form")

            function initialize() {
                var mapOptions = {
                    center: new google.maps.LatLng(38.03555, -78.50333),
                    zoom: 15
                };

                map = new google.maps.Map(document.getElementById("map"), mapOptions);

                google.maps.event.addListener(map, 'click', function (event) {
                    placeMarker(event.latLng);
                });
            }

            function placeMarker(location) {
                if (marker) {  // if marker exists, remove it
                    marker.setMap(null);
                }
                marker = new google.maps.Marker({
                    position: location,
                    map: map
                });

                // Update the hidden form fields with the clicked coordinates
                document.getElementById('id_longitude').value = location.lng();
                document.getElementById('id_latitude').value = location.lat();
            }

            form.addEventListener("submit", function (event) {
                // Check if latitude and longitude are empty
                var latitude = document.getElementById('id_latitude').value;
                var longitude = document.getElementById('id_longitude').value;

                // Error message element
                var errorMessage = document.getElementById("error-message");

                if (!latitude || !longitude) {
                    // Display an error message
                    errorMessage.style.display = 'flex';
                    errorMessage.style.color = "red";

                    // Prevent form submission
                    event.preventDefault();
                }
            });

            // TO-DO: add error check if marker isn't placed
            // This function will be called once the Google Maps script is loaded
            initialize();
        </script>
</body>
{% endblock content %}

geoGuess/templates/user/daily_challenge_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style>
  .challenge-tile {
    border-radius: 8px;
    overflow: hidden;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    position: relative;
    text-decoration: none;
    color: inherit;
    margin-bottom: 16px; /* space between the current challenge and the list */
  }

  .challenge-tile.large {
    width: 50%; /* full width */
    height: 300px; /* larger height */
    margin: 0 auto;
    display: block;
  }

  .challenge-tile.small {
    width: 200px; /* or whatever width you want for the smaller tiles */
    height: 150px; /* fixed height for the smaller tiles */
  }

  .challenge-image {
    width: 100%;
    height: 100%;
    background-size: cover;
    background-position: center;
    filter: blur(8px);
  }

  .challenge-date {
    padding: 8px;
    text-align: center;
    background-color: rgba(255, 255, 255, 0.85); /* semi-transparent overlay */
    position: absolute;
    bottom: 0;
    left: 0;
    width: 100%;
  }

  .challenge-list {
    display: flex;
    flex-wrap: wrap;
    gap: 16px; /* space between tiles */
    padding: 0;
    list-style: none;
    margin-top: 16px; /* space after the current challenge */
  }
</style>

<body>
    <title>Daily Challenges</title>
    <link rel="stylesheet" href="{% static 'geoGuess.css' %}" type="text/css" />
    
    <div class="text-center my-3">
        <h1>Daily Challenges</h1>
    </div>
    <!-- Current Day's Challenge -->
    {% with current_day_challenge=daily_challenge_list|dictsortreversed:"timestamp"|first %}
    <div class="challenge-tile large">
        <a href="{% url 'daily_challenge' current_day_challenge.id %}">
            <div class="challenge-image" style="background-image: url('{{ current_day_challenge.challenge.image.url }}');"></div>
            <div class="challenge-date">Today</div>
        </a>
    </div>
    {% endwith %}

    <!-- Previous Challenges -->
    <div class="container-fluid text-center my-5">
        <div class="row justify-content-center">
            {% with sorted_challenges=daily_challenge_list|dictsortreversed:"timestamp" %}
            {% for daily_challenge in sorted_challenges %}
            {% if not forloop.first %} <!-- Skip the first one since it's already displayed above -->
            <div class="col-auto challenge-tile small mb-3 mx-3">
                <a href="{% url 'daily_challenge' daily_challenge.id %}">
                    <div class="challenge-image" style="background-image: url('{{ daily_challenge.challenge.image.url }}');"></div>
                    <div class="challenge-date">{{ daily_challenge.timestamp|date:"F d, Y" }}</div>
                </a>
            </div>
            {% endif %}
            {% empty %}
            <div class="col text-center">No previous daily challenges available.</div>
            {% endfor %}
            {% endwith %}
        </div>
    </div>
</body>
{% endblock content %}